### ISSUE TITLE
Widget does not update

### ISSUE THREAD

**Issue by doubleopinter** [twofas/2fas-ios#71]
I use the widget for a few often used accounts but I've noticed that quite often the code will show that it is really out of date. For example now it is 44min and it does not update. I have to always open the app to get the actual code. 

I'm on latest iOS on a 14 Pro.

**Comment by 2fas-com** [comment]
It seems there is some issue with refreshing. The widget module will be rewritten in version 5.3.0, which is scheduled for release within a month. We will revisit this issue after the changes to see if the problem persists.

**Comment by warwickmm** [comment]
Related to #14.

**Comment by adocyn** [comment]
We've released new version although widgets for 2FA are a bit of a stretch of what the app can do with a very limited widgets functionality on iOS. It's possible to get non-refreshing tokens or timer which goes up. It should correct itself after about minute or two (sometimes longer). Sometimes locking and unlocking screen helps. Or a reboot if nothing else works. Yeah, not ideal, but we're doing the best we can with it.

**Comment by ahamro** [comment]
In version 5.3.7 the bug is still there.

![2fas](https://github.com/twofas/2fas-ios/assets/71564034/198969a0-ca9f-4aaf-9779-a266f525b1ab)

I tried Bitwarden's companion app and it does *not* show this behaviour. And also very convenient: it has a watch complication.
But still I'd prefer to start using 2FAS.
